"""add department to claims

Revision ID: 9438437b96d4
Revises: fba45aab5c2f
Create Date: 2026-05-05 21:17:43.084276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9438437b96d4'
down_revision: Union[str, Sequence[str], None] = 'fba45aab5c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('department', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_claims_department'), 'claims', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_department'), table_name='claims')
    op.drop_column('claims', 'department')
    # ### end Alembic commands ###
