"""add hashed_password to staff

Revision ID: fba45aab5c2f
Revises: 91dc4302794f
Create Date: 2026-04-27 09:41:23.158673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba45aab5c2f'
down_revision: Union[str, Sequence[str], None] = '91dc4302794f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('hashed_password', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'hashed_password')
    # ### end Alembic commands ###
